#!/usr/bin/env python3
"""
Generate SRP-PHAT coarse TDOA LUT and pair geometry for STM32 firmware.

Output:
  START/User/Algorithm/ai_srp_lut.c
"""

from itertools import combinations
import os

import numpy as np

# Physical microphone coordinates (mm), centered at (50, 50)
MIC_COORDS_MM = np.array([
    [65.00, 50.00],   # ID1
    [36.45, 62.41],   # ID2
    [51.85, 28.87],   # ID3
    [64.43, 68.82],   # ID4
    [24.42, 45.47],   # ID5
    [73.68, 34.94],   # ID6
    [42.21, 78.97],   # ID7
    [35.33, 21.76],   # ID8
    [81.51, 61.51],   # ID9
    [17.48, 63.42],   # ID10
    [65.57, 16.72],   # ID11
    [61.44, 86.49],   # ID12
    [15.66, 30.10],   # ID13
    [90.12, 41.18],   # ID14
    [25.60, 84.71],   # ID15
    [44.38, 6.63],    # ID16
], dtype=np.float64)

# Mapping: physical ID(n) -> SAI TDM channel (0-based)
MIC_CHANNEL_MAP = [
    5, 4, 7, 6, 3, 2, 1, 0,
    9, 8, 11, 10, 13, 12, 15, 14,
]

MIC_CENTER_MM = np.array([50.0, 50.0], dtype=np.float64)
SPEED_OF_SOUND = 343.0
PAIR_COUNT = 40

# 8x8 coarse grid
COARSE_ANGLES_DEG = np.array([-60.0, -45.0, -30.0, -15.0, 0.0, 15.0, 30.0, 45.0], dtype=np.float64)
COARSE_GRID_SIZE = int(COARSE_ANGLES_DEG.size)

OUTPUT_PATH = os.path.normpath(
    os.path.join(os.path.dirname(__file__), "..", "START", "User", "Algorithm", "ai_srp_lut.c")
)


def build_channel_coords_m() -> np.ndarray:
    """Return coordinates indexed by SAI channel, units in meters."""
    if len(MIC_CHANNEL_MAP) != len(MIC_COORDS_MM):
        raise ValueError("MIC_CHANNEL_MAP length must equal MIC_COORDS_MM length")
    if len(set(MIC_CHANNEL_MAP)) != len(MIC_CHANNEL_MAP):
        raise ValueError("MIC_CHANNEL_MAP has duplicate channel indices")

    coords_rel_m = (MIC_COORDS_MM - MIC_CENTER_MM) / 1000.0
    coords_by_ch = np.zeros_like(coords_rel_m)
    for phys_idx, sai_ch in enumerate(MIC_CHANNEL_MAP):
        coords_by_ch[sai_ch] = coords_rel_m[phys_idx]
    return coords_by_ch


def select_longest_pairs(coords_m: np.ndarray):
    """Select PAIR_COUNT longest baselines from all C(16,2) pairs."""
    pairs = list(combinations(range(coords_m.shape[0]), 2))
    baseline = []
    for i, j in pairs:
        dx = coords_m[i, 0] - coords_m[j, 0]
        dy = coords_m[i, 1] - coords_m[j, 1]
        dist = np.hypot(dx, dy)
        baseline.append((dist, i, j, dx, dy))

    baseline.sort(key=lambda x: x[0], reverse=True)
    sel = baseline[:PAIR_COUNT]

    pair_idx = [(it[1], it[2]) for it in sel]
    pair_dx = np.array([it[3] for it in sel], dtype=np.float64)
    pair_dy = np.array([it[4] for it in sel], dtype=np.float64)
    return pair_idx, pair_dx, pair_dy


def compute_coarse_tdoa(pair_dx: np.ndarray, pair_dy: np.ndarray) -> np.ndarray:
    """tdoa[grid_idx, pair_idx], seconds."""
    theta_rad = np.deg2rad(COARSE_ANGLES_DEG)
    phi_rad = np.deg2rad(COARSE_ANGLES_DEG)

    total = COARSE_GRID_SIZE * COARSE_GRID_SIZE
    tdoa = np.zeros((total, PAIR_COUNT), dtype=np.float64)

    for ti, th in enumerate(theta_rad):
        sth = np.sin(th)
        for pi, ph in enumerate(phi_rad):
            cph = np.cos(ph)
            sph = np.sin(ph)
            grid_idx = ti * COARSE_GRID_SIZE + pi
            tdoa[grid_idx, :] = (pair_dx * sth * cph + pair_dy * sph) / SPEED_OF_SOUND

    return tdoa


def ff(v: float) -> str:
    if abs(v) < 1.0e-15:
        return "0.0f"
    return f"{v:.10e}f"


def emit_c(pair_idx, pair_dx, pair_dy, tdoa) -> str:
    lines = []
    lines.append("/* Auto-generated by tools/generate_srp_lut.py. Do not edit manually. */")
    lines.append('#include "ai_srp_lut.h"')
    lines.append("")

    lines.append(f"const uint8_t srp_pair_idx[{PAIR_COUNT}][2] = {{")
    for i, (a, b) in enumerate(pair_idx):
        comma = "," if i < PAIR_COUNT - 1 else ""
        lines.append(f"    {{{a:2d}, {b:2d}}}{comma}")
    lines.append("};")
    lines.append("")

    lines.append(f"const float32_t srp_pair_dx[{PAIR_COUNT}] = {{")
    for i in range(0, PAIR_COUNT, 4):
        chunk = ", ".join(ff(v) for v in pair_dx[i:i + 4])
        comma = "," if (i + 4) < PAIR_COUNT else ""
        lines.append(f"    {chunk}{comma}")
    lines.append("};")
    lines.append("")

    lines.append(f"const float32_t srp_pair_dy[{PAIR_COUNT}] = {{")
    for i in range(0, PAIR_COUNT, 4):
        chunk = ", ".join(ff(v) for v in pair_dy[i:i + 4])
        comma = "," if (i + 4) < PAIR_COUNT else ""
        lines.append(f"    {chunk}{comma}")
    lines.append("};")
    lines.append("")

    angle_vals = ", ".join(f"{a:.1f}f" for a in COARSE_ANGLES_DEG)
    lines.append(f"const float32_t coarse_theta_deg[{COARSE_GRID_SIZE}] = {{{angle_vals}}};")
    lines.append(f"const float32_t coarse_phi_deg[{COARSE_GRID_SIZE}] = {{{angle_vals}}};")
    lines.append("")

    total = COARSE_GRID_SIZE * COARSE_GRID_SIZE
    lines.append(f"const float32_t tdoa_coarse_lut[{total}][{PAIR_COUNT}] = {{")
    for g in range(total):
        lines.append("    {")
        for p in range(0, PAIR_COUNT, 4):
            chunk = ", ".join(ff(v) for v in tdoa[g, p:p + 4])
            comma = "," if (p + 4) < PAIR_COUNT else ""
            lines.append(f"        {chunk}{comma}")
        comma = "," if g < total - 1 else ""
        lines.append(f"    }}{comma}")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    coords_m = build_channel_coords_m()
    pair_idx, pair_dx, pair_dy = select_longest_pairs(coords_m)
    tdoa = compute_coarse_tdoa(pair_dx, pair_dy)

    source = emit_c(pair_idx, pair_dx, pair_dy, tdoa)
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(source)

    print("Generated:", OUTPUT_PATH)
    print("Grid points:", COARSE_GRID_SIZE * COARSE_GRID_SIZE)
    print("Pairs:", PAIR_COUNT)


if __name__ == "__main__":
    main()

